[deploy]
bucket = 'cfn-artifacts-752023216802-23'
region = 'ca-central-1'
stack_name = 'CrdDb'

[parameters]
NetworkingStack = 'CrdNet'
ClusterStack = 'CrdCluster'
MasterUsername = 'cruddurroot'
MasterUserPassword = 'Eloka200'