[deploy]
bucket = 'cfn-artifacts-752023216802-23'
region = 'ca-central-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'EmmanuelELOKA/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cruddur-artifacts-752023216802"
BuildSpec = 'backend-flask/buildspec.yml'