[deploy]
bucket = 'cfn-artifacts-752023216802-23'
region = 'ca-central-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:752023216802:certificate/c1f135c1-389b-462f-afe8-09040dddd902'
WwwBucketName = 'www.roydemusglobalshipping.com'
RootBucketName = 'roydemusglobalshipping.com'